// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGcrPpvIcKHBew_esP7xnOfBDfglY3XLA',
    appId: '1:867883904457:web:e16c7d8fe8153d389c0c18',
    messagingSenderId: '867883904457',
    projectId: 'note-app-fc524',
    authDomain: 'note-app-fc524.firebaseapp.com',
    storageBucket: 'note-app-fc524.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqztRMRaC1Nh5DTWYnNJUSk2R9DNoFUXw',
    appId: '1:867883904457:android:0e3c7dbd064c54249c0c18',
    messagingSenderId: '867883904457',
    projectId: 'note-app-fc524',
    storageBucket: 'note-app-fc524.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDL2uR5KYQHrr0cST87fYNgL1KPWmJgc90',
    appId: '1:867883904457:ios:17cf8b4fc60aec6f9c0c18',
    messagingSenderId: '867883904457',
    projectId: 'note-app-fc524',
    storageBucket: 'note-app-fc524.appspot.com',
    iosBundleId: 'com.example.newsApp',
  );
}
